In [1]:
import numpy as np

In [15]:
#Tensor de Tensões
s = np.array([[50,30,20],
             [30,-20,-10],
              [20,-10,10]])
s

array([[ 50,  30,  20],
       [ 30, -20, -10],
       [ 20, -10,  10]])

In [22]:
#Tensao Média
def tensaomedia(s):
  sm = (1/3)*(s[0,0]+s[1,1]+s[2,2])
  sm = round(sm,2)
  return sm

sm = tensaomedia(s)
sm

13.33

In [12]:
#Tensor Hidrostático
shid = np.dot(sm,np.eye(3))
shid

array([[13.33,  0.  ,  0.  ],
       [ 0.  , 13.33,  0.  ],
       [ 0.  ,  0.  , 13.33]])

In [13]:
#Tensor Distorcional
sij = s - shid
sij

array([[ 36.67,  30.  ,  20.  ],
       [ 30.  , -33.33, -10.  ],
       [ 20.  , -10.  ,  -3.33]])

In [23]:
#Tensao media do tensor distorcional
smsij = tensaomedia(sij)
smsij

0.0